# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
brace_style = "SameLineWhere"
chain_width = 60
comment_width = 80
control_brace_style = "AlwaysSameLine"
edition = "2021"
empty_item_single_line = false
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = true
hard_tabs = false
indent_style = "Block"
max_width = 80
merge_derives = true
merge_imports = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
tab_spaces = 2
trailing_comma = "Never"
trailing_semicolon = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
wrap_comments = true
