[package]
name = "rust-match-made-in-hell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
parking_lot = "0.12.1"
crossbeam = "0.8.2"
tokio = "1.29.1"
futures = "0.3"
